sandbox01/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

sandbox01/sandbox01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls')),
]

sandbox01/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
   path("", views.index, name="index"),
   path("add/", views.add, name="add"),
]

sandbox01/tasks/models.py
from django.db import models

# Create your models here.

sandbox01/newyear/views.py
from django.utils import timezone
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    date = timezone.localdate()
    return render(request, "newyear.html", {
	"newyear" : (date.day == 1 and date.month == 1)
    })

sandbox01/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse

tasks = ['foo', 'bar', 'baz']

def index(request):
    return render(request, "tasks/index.html", {
	"tasks": tasks
    })

def add(request):
    return render(request, "tasks/add.html")

sandbox01/newyear/templates/newyear.html
<!DOCTYPE html>

<html>
	<head>
		<title>Is it new year?</title>
		<style>
			html, body {
				margin: 0;
				min-height: 100vh;
			}
			body {			
				display: grid;
				place-items: center;
			}
			h1 {
				font-size: 5rem;
			}
		</style>
	</head>
	<body>
		{% if newyear %}
			<h1>Yes</h1>
		{% else %}
			<h1>No</h1>
		{% endif %}
	</body>
</html>

sandbox01/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
   <h1>Add Task</h1>
	<form action="{% url 'tasks:add' %}" method="post">
	    <--! CSRF token generate !-->
    	    {% csrf_token %}
	    <input type="text" name="task">
            <input type="submit">
	</form>
   <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

sandbox01/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
	{% for task in tasks %}
	    <li>{{task}}</li>
	{% endfor %}
    </ul>

    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

sandbox01/tasks/templates/tasks/layout.html
<!DOCTYPE html>

<html>
	<head>
		<title>Tasks</title>
	</head>
	<body>
		{% block body %}
		{% endblock %}
	</body>
</html>